### ISSUE TITLE
How to use with a data frame?

### ISSUE THREAD

**Issue by benmarwick** [hadley/colformat#12]
I'm looking forward to use this to present tables via data frames. But I can't seem to see a data frame method in the pkg so far, and this doesn't work:

```
colformat.data.frame <- function(x, ...){
  x[] <- lapply(x, colformat)
  x
}

xx <- colformat(antibiotic[, 2:4])
str(xx)
```

So I'm curious to know how we can format columns in a dataframe with these methods. Thanks!

**Comment by hadley** [comment]
It's not currently possible. You'd need to `colformat()`, then `format()`, then paste the results together.  

We will probably provide some helper functions to do this, but the context is mainly improving the printing of tibbles.

**Comment by ijlyttle** [comment]
Let me ask a question here, just for my own clarification. 

Is it (will it be) the purpose of __colformat__ to establish the methods that custom classes will have to implement in order to be printed in a tibble? 

I strongly suspect the answer is yes, but I want to make sure I am keeping an eye on the right place.

FWIW, my use case is https://github.com/eddelbuettel/nanotime.

**Comment by hadley** [comment]
@ijlyttle yes

**Comment by krlmlr** [comment]
tibble is now using colformat.
